# Generated by Django 5.2 on 2025-04-22 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_bookorder_bookview'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='orders',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
